"""
Descriptions of ABI products from the NOAA github page here:
https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-goes16
"""

descriptions = {
    ("ABI", "L1b", "RadF"): "ABI Level 1b Full Disk",
    ("ABI", "L1b", "RadC"): "ABI Level 1b CONUS",
    ("ABI", "L1b", "RadM"): "ABI Level 1b Mesoscale",
    ("ABI", "L2", "ACHAC"): "ABI Level 2 Cloud Top Height CONUS",
    ("ABI", "L2", "ACHAF"): "ABI Level 2 Cloud Top Height Full Disk",
    ("ABI", "L2", "ACHAM"): "ABI Level 2 Cloud Top Height Mesoscale",
    ("ABI", "L2", "ACHTF"): "ABI Level 2 Cloud Top Temperature Full Disk",
    ("ABI", "L2", "ACHTM"): "ABI Level 2 Cloud Top Temperature Mesoscale",
    ("ABI", "L2", "ACMC"): "ABI Level 2 Clear Sky Mask CONUS",
    ("ABI", "L2", "ACMF"): "ABI Level 2 Clear Sky Mask Full Disk",
    ("ABI", "L2", "ACMM"): "ABI Level 2 Clear Sky Mask Mesoscale",
    ("ABI", "L2", "ACTPC"): "ABI Level 2 Cloud Top Phase CONUS",
    ("ABI", "L2", "ACTPF"): "ABI Level 2 Cloud Top Phase Full Disk",
    ("ABI", "L2", "ACTPM"): "ABI Level 2 Cloud Top Phase Mesoscale",
    ("ABI", "L2", "ADPC"): "ABI Level 2 Aerosol Detection CONUS",
    ("ABI", "L2", "ADPF"): "ABI Level 2 Aerosol Detection Full Disk",
    ("ABI", "L2", "ADPM"): "ABI Level 2 Aerosol Detection Mesoscale",
    ("ABI", "L2", "AICEF"): "Ice Concentration and Extent",
    ("ABI", "L2", "AITAF"): "Ice Age and Thickness",
    ("ABI", "L2", "AODC"): "ABI Level 2 Aerosol Optical Depth CONUS",
    ("ABI", "L2", "AODF"): "ABI Level 2 Aerosol Optical Depth Full Disk",
    ("ABI", "L2", "BRFC"): "Land Surface Bidirectional Reflectance Factor (CONUS) 2 km resolution & DQFs",
    ("ABI", "L2", "BRFF"): "Land Surface Bidirectional Reflectance Factor (Full Disk) 2 km resolution & DQFs",
    ("ABI", "L2", "BRFM"): "Land Surface Bidirectional Reflectance Factor (Mesoscale) 2 km resolution & DQFs",
    ("ABI", "L2", "CMIPC"): "ABI Level 2 Cloud and Moisture Imagery CONUS",
    ("ABI", "L2", "CMIPF"): "ABI Level 2 Cloud and Moisture Imagery Full Disk",
    ("ABI", "L2", "CMIPM"): "ABI Level 2 Cloud and Moisture Imagery Mesoscale",
    ("ABI", "L2", "CODC"): "ABI Level 2 Cloud Optical Depth CONUS",
    ("ABI", "L2", "CODF"): "ABI Level 2 Cloud Optical Depth Full Disk",
    ("ABI", "L2", "CPSC"): "ABI Level 2 Cloud Particle Size CONUS",
    ("ABI", "L2", "CPSF"): "ABI Level 2 Cloud Particle Size Full Disk",
    ("ABI", "L2", "CPSM"): "ABI Level 2 Cloud Particle Size Mesoscale",
    ("ABI", "L2", "CTPC"): "ABI Level 2 Cloud Top Pressure CONUS",
    ("ABI", "L2", "CTPF"): "ABI Level 2 Cloud Top Pressure Full Disk",
    ("ABI", "L2", "DMWC"): "ABI Level 2 Derived Motion Winds CONUS",
    ("ABI", "L2", "DMWF"): "ABI Level 2 Derived Motion Winds Full Disk",
    ("ABI", "L2", "DMWM"): "ABI Level 2 Derived Motion Winds Mesoscale",
    ("ABI", "L2", "DMWVC"): "L2+ Derived Motion Winds - Vapor CONUS",
    ("ABI", "L2", "DMWVF"): "L2+ Derived Motion Winds - Vapor Full Disk",
    ("ABI", "L2", "DMWVF"): "L2+ Derived Motion Winds - Vapor Mesoscale",
    ("ABI", "L2", "DSIC"): "ABI Level 2 Derived Stability Indices CONUS",
    ("ABI", "L2", "DSIF"): "ABI Level 2 Derived Stability Indices Full Disk",
    ("ABI", "L2", "DSIM"): "ABI Level 2 Derived Stability Indices Mesoscale",
    ("ABI", "L2", "DSRC"): "ABI Level 2 Downward Shortwave Radiation CONUS",
    ("ABI", "L2", "DSRF"): "ABI Level 2 Downward Shortwave Radiation Full Disk",
    ("ABI", "L2", "DSRM"): "ABI Level 2 Downward Shortwave Radiation Mesoscale",
    ("ABI", "L2", "FDCC"): "ABI Level 2 Fire (Hot Spot Characterization) CONUS",
    ("ABI", "L2", "FDCF"): "ABI Level 2 Fire (Hot Spot Characterization) Full Disk",
    ("ABI", "L2", "FDCM"): "ABI Level 2 Fire (Hot Spot Characterization) Mesoscale",
    ("ABI", "L2", "LSAC"): "Land Surface Albedo (CONUS) 2km resolution & DQFs",
    ("ABI", "L2", "LSAF"): "Land Surface Albedo (Full Disk) 2km resolution & DQFs",
    ("ABI", "L2", "LSAM"): "Land Surface Albedo (Mesoscale) 2km resolution & DQFs",
    ("ABI", "L2", "LSTC"): "ABI Level 2 Land Surface Temperature CONUS",
    ("ABI", "L2", "LSTF"): "ABI Level 2 Land Surface Temperature Full Disk",
    ("ABI", "L2", "LSTM"): "ABI Level 2 Land Surface Temperature Mesoscale",
    ("ABI", "L2", "LVMPC"): "ABI Level 2 Legacy Vertical Moisture Profile CONUS",
    ("ABI", "L2", "LVMPF"): "ABI Level 2 Legacy Vertical Moisture Profile Full Disk",
    ("ABI", "L2", "LVMPM"): "ABI Level 2 Legacy Vertical Moisture Profile Mesoscale",
    ("ABI", "L2", "LVTPC"): "ABI Level 2 Legacy Vertical Temperature Profile CONUS",
    ("ABI", "L2", "LVTPF"): "ABI Level 2 Legacy Vertical Temperature Profile Full Disk",
    ("ABI", "L2", "LVTPM"): "ABI Level 2 Legacy Vertical Temperature Profile Mesoscale",
    ("ABI", "L2", "MCMIPC"): "ABI Level 2 Cloud and Moisture Imagery CONUS",
    ("ABI", "L2", "MCMIPF"): "ABI Level 2 Cloud and Moisture Imagery Full Disk",
    ("ABI", "L2", "MCMIPM"): "ABI Level 2 Cloud and Moisture Imagery Mesoscale",
    ("ABI", "L2", "RRQPEF"): "ABI Level 2 Rainfall Rate (Quantitative Precipitation Estimate) Full Disk",
    ("ABI", "L2", "RSRC"): "ABI Level 2 Reflected Shortwave Radiation Top-Of-Atmosphere CONUS",
    ("ABI", "L2", "RSRF"): "ABI Level 2 Reflected Shortwave Radiation Top-Of-Atmosphere Full Disk",
    ("ABI", "L2", "SSTF"): "ABI Level 2 Sea Surface (Skin) Temperature Full Disk",
    ("ABI", "L2", "TPWC"): "ABI Level 2 Total Precipitable Water CONUS",
    ("ABI", "L2", "TPWF"): "ABI Level 2 Total Precipitable Water Full Disk",
    ("ABI", "L2", "TPWM"): "ABI Level 2 Total Precipitable Water Mesoscale",
    ("ABI", "L2", "VAAF"): "ABI Level 2 Volcanic Ash: Detection and Height Full Disk",
    ("EXIS", "L1b", "SFEU"): "EXIS-Solar Flux: EUV",
    ("EXIS", "L1b", "SFXR"): "EXIS-Solar Flux: X-Ray",
    ("GLM", "L2", "LCFA"): "GLM Level 2 Lightning Detection",
    ("MAG", "L1b", "GEOF"): "MAG-Geomagnetic Field",
    ("SEIS", "L1b", "EHIS"): "SEISS-Energetic Heavy Ions",
    ("SEIS", "L1b", "MPSH"): "SEISS-Mag. Electrons & Protons: Med & High Energy",
    ("SEIS", "L1b", "MPSL"): "SEISS-Mag. Electrons & Protons: Low Energy",
    ("SEIS", "L1b", "SGPS"): "SEISS-Solar & Galactic Protons",
    ("SUVI", "L1b", "Fe093"): "SUVI Level 1b Extreme Ultraviolet",
    ("SUVI", "L1b", "Fe131"): "SUVI Level 1b Extreme Ultraviolet",
    ("SUVI", "L1b", "Fe171"): "SUVI Level 1b Extreme Ultraviolet",
    ("SUVI", "L1b", "Fe195"): "SUVI Level 1b Extreme Ultraviolet",
    ("SUVI", "L1b", "Fe284"): "SUVI Level 1b Extreme Ultraviolet",
    ("SUVI", "L1b", "He303"): "SUVI Level 1b Extreme Ultraviolet",
    }
